export * from './DealsOfTheMonthSkeleton'
export * from './NewArrivalsSkeleton'
export * from './ShopPageSkeleton'
export * from './ProductPageSkeleton'
export * from './TimerSelecton'
export * from './InstagramSkeleton'
export * from './ProductShowcaseSkeleton'