import type { Metadata } from "next";
import { Playfair_Display, Poppins } from "next/font/google"; //, Oxanium
import "./globals.css";
import { QueryProvider } from "@/src/providers/QueryProvider";
import { AuthProvider } from "../providers/AuthProvider";
import { Toaster } from 'sonner';

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  variable: "--font-poppins",
  display: "swap",
});

// const oxanium = Oxanium({
//   subsets: ['latin'],
//   weight: ['400', '700'],
//   variable: '--font-oxanium',
//   display: 'swap',
// })

export const metadata: Metadata = {
  title: "FASCO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair.className} ${poppins.className} bg-white text-black`}
    >
      <body>
        <QueryProvider>
          <AuthProvider>{children}
            <Toaster position="bottom-right" richColors />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
